package com.novahire.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents one complete interview session.
 *
 * <p>Lifecycle:
 * <pre>
 *   CREATED  →  IN_PROGRESS  →  COMPLETED
 *                     ↓
 *                 CANCELLED
 * </pre>
 *
 * <p>Sprint 2  — creates the session (config saved to DB)
 * <p>Sprint 3  — populates {@code questions} via Gemini API
 * <p>Sprint 4  — populates {@code score}, {@code overallFeedback} via AI evaluation
 * <p>Sprint 5  — reads {@code completedAt}, {@code score} for history & statistics
 */
@Entity
@Table(name = "interviews", indexes = {
    @Index(name = "idx_interview_user_id",    columnList = "user_id"),
    @Index(name = "idx_interview_status",     columnList = "status"),
    @Index(name = "idx_interview_created_at", columnList = "created_at")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Interview {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ── Ownership ──────────────────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // ── Configuration (set at creation, read by AI in Sprint 3) ───────────────

    /**
     * Job role the user is practicing for.
     * Sprint 3 Gemini prompt: "Generate {questionCount} interview questions
     * for a {experienceLevel} {targetRole} developer..."
     */
    @Column(nullable = false, length = 100)
    private String targetRole;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ExperienceLevel experienceLevel;

    /**
     * Technology stack for this session.
     * Stored as a separate join table so Sprint 3 can iterate cleanly
     * without string-splitting. Each value is a plain tech name: "Java", "React".
     */
    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
        name = "interview_technologies",
        joinColumns = @JoinColumn(name = "interview_id")
    )
    @Column(name = "technology", length = 50)
    @Builder.Default
    private List<String> technologies = new ArrayList<>();

    /** Planned session length — used to control question count in Sprint 3. */
    @Column(nullable = false)
    @Builder.Default
    private Integer durationMinutes = 30;

    /**
     * Language for question generation.
     * Stored as enum name: ENGLISH | FRENCH | ARABIC.
     */
    @Column(nullable = false, length = 20)
    @Builder.Default
    private String language = "ENGLISH";

    /**
     * Controls the category mix in the AI prompt (Sprint 4).
     * Null for interviews created before Sprint 4 — treated as MIXED at generation time.
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 30)
    @Builder.Default
    private InterviewStyle interviewStyle = InterviewStyle.MIXED;

    // ── AI-generated content (null until Sprint 3) ────────────────────────────

    /**
     * Number of questions the AI should generate.
     * Derived from durationMinutes (approx. 1 question per 5 min) in Sprint 3.
     */
    @Column
    private Integer questionCount;

    /**
     * Raw AI prompt snapshot — stored so we can reproduce/debug generation.
     * Set by Sprint 3 GeminiService.
     */
    @Column(columnDefinition = "TEXT")
    private String aiPromptSnapshot;

    // ── Evaluation (null until Sprint 4) ──────────────────────────────────────

    /** Aggregate score 0–100, weighted average of per-question scores. */
    @Column
    private Integer score;

    /**
     * High-level AI narrative: strengths, weaknesses, top recommendations.
     * Generated by Sprint 4 evaluation pass.
     */
    @Column(columnDefinition = "TEXT")
    private String overallFeedback;

    // ── State machine ──────────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private Status status = Status.CREATED;

    // ── Timestamps ─────────────────────────────────────────────────────────────

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();

    /** Set when status transitions to COMPLETED. */
    @Column
    private LocalDateTime completedAt;

    /**
     * Set once, on the CREATED → IN_PROGRESS transition (first session load).
     * Sole anchor for the client-side countdown: startedAt + durationMinutes.
     */
    @Column
    private LocalDateTime startedAt;

    @PreUpdate
    public void preUpdate() { this.updatedAt = LocalDateTime.now(); }

    // ── Enums ──────────────────────────────────────────────────────────────────

    public enum Status {
        CREATED,      // config saved, not started
        IN_PROGRESS,  // user is answering questions
        COMPLETED,    // all answers submitted + AI scored
        CANCELLED     // user abandoned the session
    }

    public enum ExperienceLevel {
        JUNIOR,   // 0–2 years
        MID,      // 2–5 years
        SENIOR,   // 5–10 years
        LEAD      // 10+ years / principal / architect
    }

    /** Controls the question category mix sent to the AI prompt. */
    public enum InterviewStyle {
        MIXED,         // balanced across all categories
        TECHNICAL,     // code, algorithms, debugging-heavy
        BEHAVIORAL,    // soft skills, STAR method, communication
        SYSTEM_DESIGN  // architecture, scalability, design patterns
    }
}
